name: Cron - Sync BCNY forks

on:
  # schedule:
  # # Every day 8:00 am UTC
  #  - cron: '0 8 * * *'

  workflow_dispatch:

jobs:

  sync_analytics_swift:
    name: "Sync analytics-swift"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ secrets.FORK_SYNCER_APP_ID }}
          private-key: ${{ secrets.FORK_SYNCER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: analytics-swift
      - uses: thebrowsercompany/gha-sync-fork@73f382706ed07f29b97b055031e69e7beb6c1795
        with:
          fork_repo: thebrowsercompany/analytics-swift
          fork_branch: develop
          upstream_repo: segmentio/analytics-swift
          upstream_branch: main
          token: ${{ steps.token.outputs.token }}

  sync_firebase_cpp_sdk:
    name: "Sync firebase-cpp-sdk"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ secrets.FORK_SYNCER_APP_ID }}
          private-key: ${{ secrets.FORK_SYNCER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: firebase-cpp-sdk
      - uses: thebrowsercompany/gha-sync-fork@73f382706ed07f29b97b055031e69e7beb6c1795
        with:
          fork_repo: thebrowsercompany/firebase-cpp-sdk
          fork_branch: compnerd/swift
          upstream_repo: firebase/firebase-cpp-sdk
          upstream_branch: main
          token: ${{ steps.token.outputs.token }}

  sync_swift_eventsource:
    runs-on: ubuntu-latest
    name: "Sync swift-eventsource"
    steps:
      - uses: actions/create-github-app-token@v1
        id: token
        with:
          app-id: ${{ secrets.FORK_SYNCER_APP_ID }}
          private-key: ${{ secrets.FORK_SYNCER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: swift-eventsource
      - uses: thebrowsercompany/gha-sync-fork@73f382706ed07f29b97b055031e69e7beb6c1795
        with:
          fork_repo: thebrowsercompany/swift-eventsource
          fork_branch: main-bcny
          upstream_repo: launchdarkly/swift-eventsource
          upstream_branch: main
          token: ${{ steps.token.outputs.token }}

